### ISSUE TITLE
Error on console 

### ISSUE THREAD

**Issue by alemedinam** [13hakta/zbxwmi#2]
I followed all steps of README.md. At the moment of execute any command, a receive  this error:

Run 
`$ /usr/lib/zabbix/externalscripts/zbxwmi -h`

Result:
`File "/usr/lib/zabbix/externalscripts/zbxwmi", line 54
    print "action 'get' requires only one item"
                                              ^
SyntaxError: Missing parentheses in call to 'print'
`
I run the Zabbix Appliance versión 4.2

**Comment by 13hakta** [comment]
Do you use python v2 for running script?

**Comment by 13hakta** [comment]
Checkout for recent updates with Python 3.
